// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  module.exports = function(validation) {
    var gh;
    gh = {
      add_team_asset: function(actor, team) {
        return validation.auth.kratos._is_kratos_admin(actor) || gh._is_gh_team_admin(actor, team);
      },
      remove_team_asset: function(actor, team) {
        return validation.auth.kratos._is_kratos_admin(actor) || gh._is_gh_team_admin(actor, team);
      },
      add_resource_role: function(actor, role) {
        return validation.auth.is_kratos_system_user(actor);
      },
      remove_resource_role: function(actor, role) {
        return validation.auth.is_kratos_system_user(actor);
      },
      _is_gh_team_admin: function(actor, team) {
        return validation.auth._has_resource_role(actor, 'gh', 'user') && validation.auth._is_team_admin(actor, team);
      }
    };
    return gh;
  };

}).call(this);
